const BOARD = 'BOARD';
const LABEL = 'LABEL';
const LIST = 'LIST';
const CARD = 'CARD';
const TASK_LIST = 'TASK_LIST';
const TASK = 'TASK';
const CUSTOM_FIELD_GROUP = 'CUSTOM_FIELD_GROUP';
const CUSTOM_FIELD = 'CUSTOM_FIELD';

export default {
  BOARD,
  LABEL,
  LIST,
  CARD,
  TASK_LIST,
  TASK,
  CUSTOM_FIELD_GROUP,
  CUSTOM_FIELD,
};
