const ADMINISTRATION = 'ADMINISTRATION';
const USER_SETTINGS = 'USER_SETTINGS';
const ADD_PROJECT = 'ADD_PROJECT';
const PROJECT_SETTINGS = 'PROJECT_SETTINGS';
const BOARD_SETTINGS = 'BOARD_SETTINGS';
const BOARD_ACTIVITIES = 'BOARD_ACTIVITIES';

export default {
  ADMINISTRATION,
  USER_SETTINGS,
  ADD_PROJECT,
  PROJECT_SETTINGS,
  BOARD_SETTINGS,
  BOARD_ACTIVITIES,
};
